### PR TITLE
feat: Add Mint module #54

### PR DESCRIPTION
**Pull request by David-Sod**

### CODE REVIEW

**Review by luis-stakeordie — COMMENTED** [review]
@David-Sod looks good. Are we sure we don't want to name the types more specific?

Those are of them returns the same response?

**Comment by luis-stakeordie** [comment]
The problem I see is that maybe other modules will have that generic name and therefore not being able to have two types with the same name across all the different modules.

Maybe naming based on the module?

**Comment by David-Sod** [comment]
You right,what do you think about `MintParamsResponse`  or `MintParametersResponse` ?

**Comment by luis-stakeordie** [comment]
Yeah I think. We might be more domain specific, but we don't really know too much about what that data means lol, so is fine.

**Review by luis-stakeordie — APPROVED** [review]
Ok this is approved.

**Pull request merged**
